# Generated by Django 5.1.6 on 2025-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('temperature', models.CharField(max_length=10)),
                ('pressure', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
            ],
        ),
    ]
